import React,{useEffect,useMemo,useState} from 'react'
import {cloudEnabled,supabase} from './supabase'
import {defaults,loadState,saveState} from './storage'
import {words,phrases} from './data'
import {quizTypes,generateQuiz} from './quiz'
import {SpeedInsights} from '@vercel/speed-insights/react'
const day=()=>new Date().toLocaleDateString('en-CA')
const id=()=>crypto.randomUUID()
function Card(p){return <section className={'card '+(p.className||'')}>{p.children}</section>}
function App(){
 const [s,setS]=useState(defaults),[ready,setReady]=useState(false),[tab,setTab]=useState('home'),[now,setNow]=useState(new Date()),[quiz,setQuiz]=useState(null),[qi,setQi]=useState(0),[score,setScore]=useState(0),[time,setTime]=useState(20),[pom,setPom]=useState(1500),[run,setRun]=useState(false)
 useEffect(()=>{loadState().then(x=>{setS(x);setPom((x.pomodoro?.work||25)*60);setReady(true)});const x=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(x)},[])
 useEffect(()=>{if(ready)saveState(s);document.documentElement.dataset.theme=s.settings?.theme||'dark'},[s,ready])
 useEffect(()=>{if(!run)return;const x=setInterval(()=>setPom(v=>{if(v<=1){setRun(false);return 0}return v-1}),1000);return()=>clearInterval(x)},[run])
 useEffect(()=>{if(!quiz)return;const x=setInterval(()=>setTime(v=>{if(v<=1){answer(null);return 20}return v-1}),1000);return()=>clearInterval(x)},[quiz,qi])
 const streak=useMemo(()=>{let n=0,d=new Date();while(s.streakDays.includes(d.toLocaleDateString('en-CA'))){n++;d.setDate(d.getDate()-1)}return n},[s.streakDays])
 const avg=s.results.length?Math.round(s.results.slice(-7).reduce((a,x)=>a+x.percent,0)/Math.min(7,s.results.length)):0
 const di=Math.floor((Date.now()-new Date('2026-01-01'))/86400000),dw=[0,1,2].map(i=>words[(di*3+i)%words.length]),dp=[0,1,2].map(i=>phrases[(di*3+i)%phrases.length])
 function start(t){const z=quizTypes.find(x=>x.id===t);setQuiz({...z,questions:generateQuiz(t,z.count)});setQi(0);setScore(0);setTime(20)}
 function answer(a){if(!quiz)return;const ok=a===quiz.questions[qi].answer,n=score+(ok?1:0);if(qi+1>=quiz.questions.length){const r={id:id(),date:day(),type:quiz.title,score:n,total:quiz.count,percent:Math.round(n/quiz.count*100)};setS(x=>({...x,results:[...x.results,r],streakDays:[...new Set([...x.streakDays,day()])]}));setQuiz(null);setTab('results')}else{setScore(n);setQi(x=>x+1);setTime(20)}}
 if(!ready)return <div className="loading">Loading KouVerse…</div>
 const add=(k,v)=>setS(x=>({...x,[k]:typeof v==='function'?v(x[k]):v}))
 return <div className="app"><SpeedInsights /><aside><div className="brand">Kou<span>Verse</span></div>{[['home','⌂','Dashboard'],['quiz','◉','Quizzes'],['results','▤','Results'],['syllabus','✓','Syllabus'],['notes','✎','Notes'],['memory','◇','English']].map(n=><button className={tab===n[0]?'nav active':'nav'} onClick={()=>setTab(n[0])} key={n[0]}><b>{n[1]}</b>{n[2]}</button>)}<button className="theme" onClick={()=>add('settings',x=>({...x,theme:x.theme==='dark'?'light':'dark'}))}>{s.settings.theme==='dark'?'☀ Bright':'☾ Dark'} theme</button><small>{cloudEnabled?'☁ Supabase enabled':'◌ Local mode'}</small></aside>
 <main><header><div><h1>{tab==='home'?'Study Command Center':tab}</h1><p>Small daily wins beat panic-revision.</p></div><div className="streak">🔥 <b>{streak} day streak</b><small>{now.toLocaleDateString()} · {now.toLocaleTimeString()}</small></div></header>
 {tab==='home'&&<div className="grid"><Card className="hero"><div><span>TODAY'S MOMENTUM</span><h2>{streak?'Keep the chain alive.':'Start your streak today.'}</h2><p>Take a timed drill, review three words and finish one task.</p></div><strong className="score">{avg}%<small>quiz avg.</small></strong></Card><Card><h3>⏱ Pomodoro</h3><div className="clock">{String(Math.floor(pom/60)).padStart(2,'0')}:{String(pom%60).padStart(2,'0')}</div><button onClick={()=>setRun(!run)}>{run?'Pause':'Start'}</button> <button className="ghost" onClick={()=>{setRun(false);setPom((s.pomodoro?.work||25)*60)}}>Reset</button></Card><Card><h3>📈 Quiz improvement</h3><div className="chart">{s.results.slice(-10).map((x,i)=><i key={i} style={{height:(x.percent||0)+'%'}}/>)}</div><b>{s.results.length}</b> attempts</Card><Card><h3>🔥 Last 28 days</h3><div className="heat">{Array.from({length:28},(_,i)=>{const d=new Date();d.setDate(d.getDate()-27+i);return <i className={s.streakDays.includes(d.toLocaleDateString('en-CA'))?'hit':''} key={i}/>})}</div></Card><Card className="wide"><h3>✅ Todo</h3><Todo s={s} setS={setS}/></Card><Card><h3>📚 Words today</h3>{dw.map(w=><div className="item" key={w[0]}><b>{w[0]}</b><span>{w[1]}</span></div>)}</Card><Card><h3>💬 Smart phrases</h3>{dp.map(p=><div className="item" key={p[0]}><b>{p[0]}</b><span>{p[1]}</span></div>)}</Card></div>}
 {tab==='quiz'&&!quiz&&<div className="quizgrid">{quizTypes.map(q=><Card key={q.id}><span className="pill">{q.count} questions</span><h3>{q.title}</h3><p>20 seconds per question</p><button onClick={()=>start(q.id)}>Start drill →</button></Card>)}</div>}
 {tab==='quiz'&&quiz&&<Card className="quizplay"><div className="qtop">Question {qi+1}/{quiz.count}<b>{time}s</b></div><div className="bar"><i style={{width:(time/20*100)+'%'}}/></div><h2>{quiz.questions[qi].prompt}</h2><div className="answers">{quiz.questions[qi].options.map(o=><button key={o} onClick={()=>answer(o)}>{o}</button>)}</div></Card>}
 {tab==='results'&&<Card><h3>Daily quiz results</h3><table><thead><tr><th>Date</th><th>Quiz</th><th>Score</th><th>Accuracy</th></tr></thead><tbody>{[...s.results].reverse().map(r=><tr key={r.id}><td>{r.date}</td><td>{r.type}</td><td>{r.score}/{r.total}</td><td>{r.percent}%</td></tr>)}</tbody></table></Card>}
 {tab==='syllabus'&&<Syllabus s={s} setS={setS}/>}
 {tab==='notes'&&<Notes s={s} setS={setS}/>}
 {tab==='memory'&&<Memory s={s} setS={setS} words={dw}/>}
 </main></div>
}
function Todo({s,setS}){const [v,setV]=useState('');function add(){if(v.trim()){setS(x=>({...x,todos:[...x.todos,{id:id(),text:v.trim(),done:false}]}));setV('')}}return <><div className="row"><input value={v} onChange={e=>setV(e.target.value)} onKeyDown={e=>e.key==='Enter'&&add()} placeholder="Add a task"/><button onClick={add}>Add</button></div>{s.todos.map(t=><div className="todo" key={t.id}><input type="checkbox" checked={t.done} onChange={()=>setS(x=>({...x,todos:x.todos.map(y=>y.id===t.id?{...y,done:!y.done}:y)}))}/><span className={t.done?'done':''}>{t.text}</span><button className="ghost" onClick={()=>setS(x=>({...x,todos:x.todos.filter(y=>y.id!==t.id)}))}>×</button></div>)}</>}
function Syllabus({s,setS}){const [x,setX]=useState({subject:'',topic:'',subtopics:'',done:0});return <Card><h3>Syllabus tracker</h3><div className="row"><input placeholder="Subject" value={x.subject} onChange={e=>setX({...x,subject:e.target.value})}/><input placeholder="Topic / subtopics" value={x.topic} onChange={e=>setX({...x,topic:e.target.value})}/><button onClick={()=>{if(x.subject)setS(v=>({...v,syllabus:[...v.syllabus,{...x,id:id()}]}));setX({subject:'',topic:'',subtopics:'',done:0})}}>Add</button></div>{s.syllabus.map(x=><div className="syll" key={x.id}><b>{x.subject}</b><span>{x.topic}</span><input type="range" min="0" max="100" value={x.done} onChange={e=>setS(v=>({...v,syllabus:v.syllabus.map(y=>y.id===x.id?{...y,done:+e.target.value}:y)}))}/><strong>{x.done}%</strong></div>)}</Card>}
function Notes({s,setS}){const [v,setV]=useState('');return <Card><h3>Quick notes / important topics</h3><textarea value={v} onChange={e=>setV(e.target.value)} placeholder="Write an important shortcut or topic…"/><button onClick={()=>{if(v.trim()){setS(x=>({...x,notes:[...x.notes,{id:id(),text:v.trim()}]}));setV('')}}}>Save note</button><div className="notes">{s.notes.map(n=><article key={n.id}>{n.text}<button className="ghost" onClick={()=>setS(x=>({...x,notes:x.notes.filter(y=>y.id!==n.id)}))}>Delete</button></article>)}</div></Card>}
function Memory({s,setS,words}){return <div className="memory">{words.map(w=><Card key={w[0]}><span className="pill">Vocabulary</span><h2>{w[0]}</h2><p>{w[1]}</p><blockquote>{w[2]}</blockquote><div className="row">{[['Again',1],['Hard',3],['Good',4],['Easy',5]].map(g=><button key={g[0]} onClick={()=>setS(x=>({...x,reviews:{...x.reviews,[w[0]]:{grade:g[1],due:Date.now()+g[1]*86400000}}}))}>{g[0]}</button>)}</div></Card>)}</div>}
export default App